name: cathycracks
favicon: null
layout_spectrum: 0.7030849407892674
typography_spectrum: 0.53695496940054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7285807142034173
  lightness: 0.43102484033443034
  saturation: 0.14051552838645875
  rhythmicContrast: 0.5302199693396688
purpose: []
